# Generated by Django 3.2 on 2024-04-12 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('aCode', models.CharField(max_length=10)),
                ('nameFr', models.CharField(max_length=250)),
                ('nameNl', models.CharField(max_length=250)),
                ('nameEn', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('env_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('env_type', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=30)),
                ('applicationId', models.ForeignKey(db_column='applicationId', default=0, on_delete=django.db.models.deletion.CASCADE, to='app.application')),
            ],
            options={
                'db_table': 'environment',
            },
        ),
    ]
